version: '3.8'

services:
  frontend:
    build:
      context: ./devops       # trỏ đến thư mục devops (Next.js project)
      dockerfile: Dockerfile  # file Dockerfile nằm trong devops
    container_name: frontend-app
    ports:
      - "3000:3000"           # ánh xạ port host:container
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: backend-app
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - app-network
  #   depends_on:
  #     - db

  # db:
  #   image: postgres:15
  #   container_name: db
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=pass
  #     - POSTGRES_DB=mydb
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
