version: '3.8'

services:
  frontend-learnking:
    build:
      context: ./devops       # đường dẫn tới thư mục chứa Dockerfile của Next.js
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/learnking-frontend:latest
    container_name: learnking-frontend
    ports:
      - "3000:3000"           # map port host 3000 -> container 3000
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
